export const rarities = {
  common: { color: 0x9fb0d9, label: 'Common' },
  rare: { color: 0x6fd3ff, label: 'Rare' },
  epic: { color: 0xc77dff, label: 'Epic' },
  legendary: { color: 0xffc857, label: 'Legendary' },
};

export function createBaseStats(meta) {
  return {
    maxHealth: 100 + meta.maxHealth * 8,
    health: 100 + meta.maxHealth * 8,
    damage: 14 + meta.damage * 1.8,
    attackRate: 0.7 + meta.attackRate * 0.05,
    critChance: 0.05 + meta.crit * 0.01,
    critDamage: 1.6,
    dashCooldown: 2.8 - meta.dashCooldown * 0.12,
    dashCharges: 1 + meta.dashCharges,
    dashSpeed: 340,
    armor: meta.armor * 0.05,
    aoeRadius: meta.aoe * 1,
    dotChance: meta.dot * 0.01,
    dotDamage: 3,
    dotDuration: 2,
    economy: 1 + meta.economy * 0.06,
    moveSpeed: 180,
  };
}

export const upgrades = [
  {
    id: 'damage-1',
    name: 'Gilded Edge',
    desc: '+12% damage',
    rarity: 'common',
    apply: (stats) => { stats.damage *= 1.12; },
  },
  {
    id: 'damage-2',
    name: 'Runebound Strike',
    desc: '+20% damage',
    rarity: 'rare',
    apply: (stats) => { stats.damage *= 1.2; },
  },
  {
    id: 'damage-3',
    name: 'Executioners Oath',
    desc: '+35% damage',
    rarity: 'epic',
    apply: (stats) => { stats.damage *= 1.35; },
  },
  {
    id: 'attack-1',
    name: 'Quickdraw',
    desc: '+12% attack rate',
    rarity: 'common',
    apply: (stats) => { stats.attackRate *= 1.12; },
  },
  {
    id: 'attack-2',
    name: 'Clockwork Focus',
    desc: '+22% attack rate',
    rarity: 'rare',
    apply: (stats) => { stats.attackRate *= 1.22; },
  },
  {
    id: 'attack-3',
    name: 'Photon Tempo',
    desc: '+35% attack rate',
    rarity: 'epic',
    apply: (stats) => { stats.attackRate *= 1.35; },
  },
  {
    id: 'crit-1',
    name: 'Opal Precision',
    desc: '+8% crit chance',
    rarity: 'rare',
    apply: (stats) => { stats.critChance += 0.08; },
  },
  {
    id: 'crit-2',
    name: 'Royal Verdict',
    desc: '+20% crit damage',
    rarity: 'epic',
    apply: (stats) => { stats.critDamage += 0.2; },
  },
  {
    id: 'crit-3',
    name: 'Merciless',
    desc: '+12% crit chance, +15% crit damage',
    rarity: 'legendary',
    apply: (stats) => { stats.critChance += 0.12; stats.critDamage += 0.15; },
  },
  {
    id: 'dash-1',
    name: 'Silkstep',
    desc: '-15% dash cooldown',
    rarity: 'common',
    apply: (stats) => { stats.dashCooldown *= 0.85; },
  },
  {
    id: 'dash-2',
    name: 'Phase Relay',
    desc: '-30% dash cooldown',
    rarity: 'rare',
    apply: (stats) => { stats.dashCooldown *= 0.7; },
  },
  {
    id: 'dash-3',
    name: 'Second Wind',
    desc: '+1 dash charge',
    rarity: 'epic',
    apply: (stats) => { stats.dashCharges += 1; },
  },
  {
    id: 'aoe-1',
    name: 'Shockwave',
    desc: '+22px AOE radius',
    rarity: 'common',
    apply: (stats) => { stats.aoeRadius += 22; },
  },
  {
    id: 'aoe-2',
    name: 'Nova Core',
    desc: '+38px AOE radius',
    rarity: 'rare',
    apply: (stats) => { stats.aoeRadius += 38; },
  },
  {
    id: 'aoe-3',
    name: 'Starfall',
    desc: '+65px AOE radius',
    rarity: 'epic',
    apply: (stats) => { stats.aoeRadius += 65; },
  },
  {
    id: 'dot-1',
    name: 'Cinder Hex',
    desc: '20% chance to burn',
    rarity: 'common',
    apply: (stats) => { stats.dotChance += 0.2; },
  },
  {
    id: 'dot-2',
    name: 'Ashen Coil',
    desc: '+3 burn damage',
    rarity: 'rare',
    apply: (stats) => { stats.dotDamage += 3; },
  },
  {
    id: 'dot-3',
    name: 'Everburn',
    desc: '+1.5s burn duration',
    rarity: 'epic',
    apply: (stats) => { stats.dotDuration += 1.5; },
  },
  {
    id: 'defense-1',
    name: 'Obsidian Plating',
    desc: '+8% damage reduction',
    rarity: 'common',
    apply: (stats) => { stats.armor += 0.08; },
  },
  {
    id: 'defense-2',
    name: 'Aegis Pulse',
    desc: '+14% damage reduction',
    rarity: 'rare',
    apply: (stats) => { stats.armor += 0.14; },
  },
  {
    id: 'defense-3',
    name: 'Fortress Sigil',
    desc: '+22% damage reduction',
    rarity: 'epic',
    apply: (stats) => { stats.armor += 0.22; },
  },
  {
    id: 'economy-1',
    name: 'Guild Charter',
    desc: '+12% gold drops',
    rarity: 'common',
    apply: (stats) => { stats.economy += 0.12; },
  },
  {
    id: 'economy-2',
    name: 'Silent Broker',
    desc: '+25% gold drops',
    rarity: 'rare',
    apply: (stats) => { stats.economy += 0.25; },
  },
  {
    id: 'economy-3',
    name: 'Golden Pact',
    desc: '+45% gold drops',
    rarity: 'epic',
    apply: (stats) => { stats.economy += 0.45; },
  },
  {
    id: 'speed-1',
    name: 'Fleet Circuit',
    desc: '+20 move speed',
    rarity: 'common',
    apply: (stats) => { stats.moveSpeed += 20; },
  },
  {
    id: 'speed-2',
    name: 'Void Stride',
    desc: '+35 move speed',
    rarity: 'rare',
    apply: (stats) => { stats.moveSpeed += 35; },
  },
  {
    id: 'vampiric-1',
    name: 'Life Tap',
    desc: 'Heal 2 on kill',
    rarity: 'rare',
    apply: (stats) => { stats.onKillHeal = (stats.onKillHeal || 0) + 2; },
  },
  {
    id: 'burst-1',
    name: 'Arc Burst',
    desc: 'Shots chain to nearby enemy',
    rarity: 'legendary',
    apply: (stats) => { stats.chainShots = (stats.chainShots || 0) + 1; },
  },
  {
    id: 'guardian-1',
    name: 'Guardian Spark',
    desc: 'Orbital shield deals contact damage',
    rarity: 'epic',
    apply: (stats) => { stats.orbitals = (stats.orbitals || 0) + 1; },
  },
  {
    id: 'health-1',
    name: 'Vigor Alloy',
    desc: '+25 max health',
    rarity: 'common',
    apply: (stats) => { stats.maxHealth += 25; stats.health += 25; },
  },
  {
    id: 'health-2',
    name: 'Titan Frame',
    desc: '+45 max health',
    rarity: 'rare',
    apply: (stats) => { stats.maxHealth += 45; stats.health += 45; },
  },
];

export const metaUpgrades = [
  {
    id: 'maxHealth',
    name: 'Vital Capsule',
    desc: '+8 max health per rank',
    cost: 60,
    maxRank: 5,
  },
  {
    id: 'damage',
    name: 'Calibrated Edge',
    desc: '+1.8 damage per rank',
    cost: 75,
    maxRank: 5,
  },
  {
    id: 'attackRate',
    name: 'Overclock',
    desc: '+5% attack rate per rank',
    cost: 70,
    maxRank: 5,
  },
  {
    id: 'dashCooldown',
    name: 'Slipstream',
    desc: '-0.12s dash cooldown per rank',
    cost: 85,
    maxRank: 4,
  },
  {
    id: 'armor',
    name: 'Composite Plate',
    desc: '+5% armor per rank',
    cost: 90,
    maxRank: 4,
  },
  {
    id: 'economy',
    name: 'Vault Interest',
    desc: '+6% gold per rank',
    cost: 60,
    maxRank: 5,
  },
  {
    id: 'crit',
    name: 'Targeting Suite',
    desc: '+1% crit chance per rank',
    cost: 80,
    maxRank: 5,
  },
  {
    id: 'aoe',
    name: 'Blast Lens',
    desc: '+1 AOE radius per rank',
    cost: 55,
    maxRank: 5,
  },
  {
    id: 'dot',
    name: 'Thermal Module',
    desc: '+1% burn chance per rank',
    cost: 55,
    maxRank: 5,
  },
  {
    id: 'dashCharges',
    name: 'Spare Core',
    desc: '+1 dash charge per rank',
    cost: 120,
    maxRank: 2,
  },
];
